### PR TITLE
Add suport to load directly from dev server

### PR DESCRIPTION
**Pull request by tadeuzagallo**
This adds support for loading apps from any given URL. The main idea is to be able to connect directly into the packager running on the computer, so you can use the app for development on the phone without being limited to the web interface (that's pretty cool, but for slightly bigger apps it's more complicated). It'd also probably be nice to enable the dev tools inside the app, so it'd be possible to do things like profiling.

The names I picked are terrible, any suggestions would be great.

ios simulator screen shot 24 jun 2015 02 23 34

### CODE REVIEW

**Comment by jsierles** [comment]
Very cool! This is an obvious feature we had not considered :)

A few things:
- We are close to releasing support for pushing git repos directly to rnplay, to make developing larger apps easier
- What do we need to do to enable dev tools?
- We should make it clear that you can only use included modules and the same version of RN as the app

We'll discuss this tomorrow on Slack #rnplay and see about integrating into the next release with 0.6.0. Do join there!

**Comment by brentvatne** [comment]
:+1: love it, maybe  "Direct URL" for name?

**Comment by tadeuzagallo** [comment]
@brentvatne Sounds good, I'll updated it.

@jsierles To enable the dev tools you have to compile it with `RCT_DEV=1`, it's off by default for release builds, but for this specific case might be a nice thing to have. If you also want to enable red box errors, you also have to add `RCT_DEBUG=1`
I'll add a note about the version and native modules.

I don't know how to Slack :disappointed:

**Comment by jsierles** [comment]
I'll enable dev mode for the next build.

We should probably list which native modules are available. Either in the app, or on the site somewhere. I'll look into that.

Other ideas:
- store entries to a list of recently used URLs. avoids typing over and over
- add a feature to the rnplay cli to generate and display an app URL QR code, since we can scan those already

**Comment by brentvatne** [comment]
:tada:

**Comment by jsierles** [comment]
This has been submitted to the app store :)

**Comment by tadeuzagallo** [comment]
Nice :) 
Sorry I couldn't iterate on the feedback faster, I'll try to follow up...

**Comment by jsierles** [comment]
No worries! Just want to get the app moving ahead so it's as up-to-date as possible for React Europe.

**Pull request merged**
